dist: focal
language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12-beta1'
  - 'pypy3'

before_install:
  - sudo apt-get -y install libzbar0

install:
  - pip install -r requirements-testing.txt
  - pip install flake8;
  - pip install mypy;

script:
  - flake8 segno;
  - flake8 tests/;
  - mypy segno;
  - pytest
